# This Dockerfile uses micromamba to install the dependencies from the lock file.
FROM mambaorg/micromamba:lunar

# Run the container as root to get access to the USB devices
USER root

WORKDIR /opt/home-assistant-streamdeck-yaml

# Install the dependencies from the lock file
COPY conda-lock.yml /opt/home-assistant-streamdeck-yaml/conda-lock.yml
RUN micromamba install --name base --file conda-lock.yml

# Install git
RUN micromamba install --name base --channel conda-forge --yes git && \
    micromamba clean --all --yes

# Copy the rest of the files
COPY . /opt/home-assistant-streamdeck-yaml/
COPY .git /opt/home-assistant-streamdeck-yaml/.git

# Install home-assistant-streamdeck-yaml
RUN micromamba run \
    pip install --no-deps -e .

WORKDIR /app
ENV STREAMDECK_CONFIG=/app/configuration.yaml

# Set the entrypoint
CMD ["home-assistant-streamdeck-yaml"]
