# This Dockerfile uses unidep to install all (unpinned) dependencies
FROM mambaorg/micromamba:lunar

# Run the container as root to get access to the USB devices
USER root

# Install unidep and git
RUN micromamba install --name base --channel conda-forge --yes unidep git
WORKDIR /opt/home-assistant-streamdeck-yaml

# Copy the dependencies file for pip
COPY . /opt/home-assistant-streamdeck-yaml/
COPY .git /opt/home-assistant-streamdeck-yaml/.git

# Install the required dependencies
RUN micromamba run \
    unidep install -e . && \
    micromamba clean --all --yes

WORKDIR /app
ENV STREAMDECK_CONFIG=/app/configuration.yaml

# Set the entrypoint
CMD ["home-assistant-streamdeck-yaml"]
