name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ github.repository }}
    permissions:
      contents: write  # for creating tags and releases
      id-token: write  # for PyPI publishing
    steps:
    - uses: basnijholt/calver-auto-release@v1
      id: release
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build package
      if: steps.release.outputs.version != ''
      run: |
        python -m pip install build
        python -m build

    - name: Publish package distributions to PyPI
      if: steps.release.outputs.version != ''
      uses: pypa/gh-action-pypi-publish@release/v1
